<a href="https://colab.research.google.com/github/Aman05gupta/Matrix_Decompositions/blob/main/Matrix_Decompositions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Eigenvalue
For a square matrix A, a scalar λ is an eigenvalue if there exists a non-zero vector v (called an eigenvector) such that Av=λv.



---


The eigenvalues of a matrix

A are found by solving the characteristic equation:  det(A−λI)=0

where

I is the identity matrix of the same dimension as A.


---


# Eigenvector:
A non-zero vector v is an eigenvector of a matrix A if there exists a scalar λ (called an eigenvalue) such that Av=λv

In [1]:
import numpy as np


In [14]:
# Define the matrix A
A = np.array([[4, 1], [2, 3]])

In [17]:
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)


In [18]:
print("Eigenvalues:", eigenvalues)

Eigenvalues: [5. 2.]


In [20]:
print("Eigenvectors:\n", eigenvectors)


Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


In [30]:
# Define the matrix A
A = np.array([[6, 2], [2, 3]])

In [31]:
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)


In [23]:
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues: [7. 2.]
Eigenvectors:
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


## Verification

In [33]:
# Verify the first eigenpair
v1 = eigenvectors[:, 0]
lambda1 = eigenvalues[0]
print("A @ v1:", A @ v1)
print("lambda1 * v1:", lambda1 * v1)




A @ v1: [6.26099034 3.13049517]
lambda1 * v1: [6.26099034 3.13049517]


In [34]:
# Verify the second eigenpair
v2 = eigenvectors[:, 1]
lambda2 = eigenvalues[1]
print("A @ v2:", A @ v2)
print("lambda2 * v2:", lambda2 * v2)

A @ v2: [-0.89442719  1.78885438]
lambda2 * v2: [-0.89442719  1.78885438]


# LU Decomposition
LU decomposition factors a matrix A into the product of a lower triangular matrix 𝐿 and an upper triangular matrix 𝑈: 𝐴 = 𝐿𝑈


---


Application: Solving systems of linear equations efficiently

In [36]:
import scipy.linalg

In [37]:
# Define the matrix A
A = np.array([[4, 3], [6, 3]])

# Perform LU decomposition
P, L, U = scipy.linalg.lu(A)

print("L:")
print(L)
print("U:")
print(U)


L:
[[1.         0.        ]
 [0.66666667 1.        ]]
U:
[[6. 3.]
 [0. 1.]]


# QR Decomposition
QR decomposition factors a matrix 𝐴 into the product of an orthogonal matrix 𝑄 and an upper triangular matrix 𝑅: 𝐴 = 𝑄𝑅


---



Application: Finding least squares solutions, eigenvalue calculations.

In [38]:
# Define the matrix A
A = np.array([[1, -1, 4], [1, 4, -2], [1, 4, 2]])

# Perform QR decomposition
Q, R = np.linalg.qr(A)

print("Q:")
print(Q)
print("R:")
print(R)


Q:
[[-5.77350269e-01  8.16496581e-01 -2.21595527e-16]
 [-5.77350269e-01 -4.08248290e-01 -7.07106781e-01]
 [-5.77350269e-01 -4.08248290e-01  7.07106781e-01]]
R:
[[-1.73205081 -4.04145188 -2.30940108]
 [ 0.         -4.0824829   3.26598632]
 [ 0.          0.          2.82842712]]


# Eigenvalue Decomposition (Eigendecomposition)
Eigendecomposition factors a matrix
𝐴 into the product of a matrix of eigenvectors 𝑉 and a diagonal matrix Λ of eigenvalues:


---


Application: Finding eigenvalues and eigenvectors.

In [39]:
# Define the matrix A
A = np.array([[6, 2], [2, 3]])

# Perform eigendecomposition
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues: [7. 2.]
Eigenvectors:
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


# Singular Value Decomposition (SVD)
SVD factors a matrix
𝐴 into the product of three matrices 𝑈, Σ, and 𝑉𝑇:

A=UΣV
where
𝑈 and 𝑉 are orthogonal matrices, and  Σ is a diagonal matrix of singular values.


---


Application: Dimensionality reduction, image compression, solving linear least squares problems.

In [40]:
# Define the matrix A
A = np.array([[1, 2], [3, 4], [5, 6]])

# Perform SVD
U, S, VT = np.linalg.svd(A)

print("U:")
print(U)
print("S (singular values):")
print(S)
print("VT (transpose of V):")
print(VT)


U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
S (singular values):
[9.52551809 0.51430058]
VT (transpose of V):
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


# Cholesky Decomposition
Cholesky decomposition factors a symmetric positive definite matrix
𝐴 into the product of a lower triangular matrix 𝐿 and its transpose:
𝐴 =𝐿𝐿𝑇

---



Application: Solving linear equations involving positive definite matrices, simulating multivariate normal distributions.

In [41]:
# Define the matrix A (symmetric positive definite)
A = np.array([[9, 3, 6], [3, 14, 2], [6, 2, 16]])

# Perform Cholesky decomposition
L = np.linalg.cholesky(A)

print("L:")
print(L)


L:
[[3.         0.         0.        ]
 [1.         3.60555128 0.        ]
 [2.         0.         3.46410162]]
